services:
  - type: web
    name: pankh-learning
    env: python
    buildCommand: bash build.sh
    startCommand: gunicorn learning_platform.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: ".onrender.com,pankh-af0o.onrender.com"
      - key: DATABASE_URL
        sync: false
    autoDeploy: true
