# Generated by Django 5.2.5 on 2025-09-02 16:36

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=courses.models.course_thumbnail_path),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_file',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.lesson_content_path),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('pdf', 'PDF'), ('audio', 'Audio'), ('interactive', 'Interactive')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
