# Generated by Django 5.2.5 on 2025-09-04 07:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_subject_grade_level_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='grade_level',
            field=models.IntegerField(choices=[(6, 'Class 6'), (7, 'Class 7'), (8, 'Class 8'), (9, 'Class 9'), (10, 'Class 10'), (11, 'Class 11'), (12, 'Class 12')], validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
